### ISSUE TITLE
How to Befriend A Turtles is not affected by frail

### ISSUE THREAD

**Issue by Residualshade** [jonasdasdefekte/The-Sage#2]

**Comment by Skrelpoid** [comment]
Currently, Frail affects the additional amount of the upgraded card. (See Below)
Is this what you meant? Or something else? What behavior would you like to see?

![picture of current behavior](https://user-images.githubusercontent.com/22478595/48500709-c58f0880-e83b-11e8-9791-91a1e8f95ac7.png)

Cheers!

**Comment by jonasdasdefekte** [comment]
The X value is not affected by Frail. It's not a bug, it's a feature ;)
