### ISSUE TITLE
Crash on acquiring any relic (from any other mod) that modifies the player character's size.

### ISSUE THREAD

**Issue by Discohydra** [jonasdasdefekte/The-Sage#21]
As it says on the tin, I even ran MTS in debug mode and got the necessary info, too.

[Sage Tiny House Shrinking Draguht debug log.txt](https://github.com/jonasdasdefekte/The-Sage/files/2725726/Sage.Tiny.House.Shrinking.Draguht.debug.log.txt)

The mod with the sprite modifying relic in question is Replay the Spire's "Shrinking Draught"

**Comment by Skrelpoid** [comment]
Hey, this crash happens outside sage's code.
If you look closely at the last part , the crash happens in `com.esotericsoftware.spine` which is for rendering the character model. Is it possible that Shrinking Draught wasn't tested with Spine animations?
